#local:
spring.application.name=harvestapp
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/HARVEST_DEV
spring.datasource.url=${HARVEST_DB_URL}
spring.datasource.username=dev
#spring.datasource.password=admin
spring.datasource.password=${HARVEST_DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema="harvest"
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10

#additional:
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect